### ISSUE TITLE
Want to change machine name

### ISSUE THREAD

**Issue by CasperLaiTW** [codeivate/codeivate-st#4]
First time I forgot change machine name.
Next I change the machine name of configuration, but website was unchanged.
So how can I correct A to B.

**Comment by p4ul** [comment]
If you update the machine name and then do some coding it should change on the website.

**Comment by CasperLaiTW** [comment]
I change the machine name and still coding. 
Website was also unchanged.
That's ok. I be waiting few hours to check.
Thank you!!!

**Comment by CasperLaiTW** [comment]
Be updated. Thank you!!!
